// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dbproto/user.proto

#ifndef PROTOBUF_dbproto_2fuser_2eproto__INCLUDED
#define PROTOBUF_dbproto_2fuser_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace db {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_dbproto_2fuser_2eproto();
void protobuf_AssignDesc_dbproto_2fuser_2eproto();
void protobuf_ShutdownFile_dbproto_2fuser_2eproto();

class UserData;

// ===================================================================

class UserData : public ::google::protobuf::Message {
 public:
  UserData();
  virtual ~UserData();

  UserData(const UserData& from);

  inline UserData& operator=(const UserData& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const UserData& default_instance();

  void Swap(UserData* other);

  // implements Message ----------------------------------------------

  UserData* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const UserData& from);
  void MergeFrom(const UserData& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 uid = 1 [default = 0];
  inline bool has_uid() const;
  inline void clear_uid();
  static const int kUidFieldNumber = 1;
  inline ::google::protobuf::int32 uid() const;
  inline void set_uid(::google::protobuf::int32 value);

  // optional string uname = 2 [default = ""];
  inline bool has_uname() const;
  inline void clear_uname();
  static const int kUnameFieldNumber = 2;
  inline const ::std::string& uname() const;
  inline void set_uname(const ::std::string& value);
  inline void set_uname(const char* value);
  inline void set_uname(const char* value, size_t size);
  inline ::std::string* mutable_uname();
  inline ::std::string* release_uname();
  inline void set_allocated_uname(::std::string* uname);

  // optional int32 money = 3 [default = 0];
  inline bool has_money() const;
  inline void clear_money();
  static const int kMoneyFieldNumber = 3;
  inline ::google::protobuf::int32 money() const;
  inline void set_money(::google::protobuf::int32 value);

  // optional int32 last_login_time = 4 [default = 0];
  inline bool has_last_login_time() const;
  inline void clear_last_login_time();
  static const int kLastLoginTimeFieldNumber = 4;
  inline ::google::protobuf::int32 last_login_time() const;
  inline void set_last_login_time(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:db.UserData)
 private:
  inline void set_has_uid();
  inline void clear_has_uid();
  inline void set_has_uname();
  inline void clear_has_uname();
  inline void set_has_money();
  inline void clear_has_money();
  inline void set_has_last_login_time();
  inline void clear_has_last_login_time();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::std::string* uname_;
  ::google::protobuf::int32 uid_;
  ::google::protobuf::int32 money_;
  ::google::protobuf::int32 last_login_time_;
  friend void  protobuf_AddDesc_dbproto_2fuser_2eproto();
  friend void protobuf_AssignDesc_dbproto_2fuser_2eproto();
  friend void protobuf_ShutdownFile_dbproto_2fuser_2eproto();

  void InitAsDefaultInstance();
  static UserData* default_instance_;
};
// ===================================================================


// ===================================================================

// UserData

// optional int32 uid = 1 [default = 0];
inline bool UserData::has_uid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void UserData::set_has_uid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void UserData::clear_has_uid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void UserData::clear_uid() {
  uid_ = 0;
  clear_has_uid();
}
inline ::google::protobuf::int32 UserData::uid() const {
  // @@protoc_insertion_point(field_get:db.UserData.uid)
  return uid_;
}
inline void UserData::set_uid(::google::protobuf::int32 value) {
  set_has_uid();
  uid_ = value;
  // @@protoc_insertion_point(field_set:db.UserData.uid)
}

// optional string uname = 2 [default = ""];
inline bool UserData::has_uname() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void UserData::set_has_uname() {
  _has_bits_[0] |= 0x00000002u;
}
inline void UserData::clear_has_uname() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void UserData::clear_uname() {
  if (uname_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    uname_->clear();
  }
  clear_has_uname();
}
inline const ::std::string& UserData::uname() const {
  // @@protoc_insertion_point(field_get:db.UserData.uname)
  return *uname_;
}
inline void UserData::set_uname(const ::std::string& value) {
  set_has_uname();
  if (uname_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    uname_ = new ::std::string;
  }
  uname_->assign(value);
  // @@protoc_insertion_point(field_set:db.UserData.uname)
}
inline void UserData::set_uname(const char* value) {
  set_has_uname();
  if (uname_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    uname_ = new ::std::string;
  }
  uname_->assign(value);
  // @@protoc_insertion_point(field_set_char:db.UserData.uname)
}
inline void UserData::set_uname(const char* value, size_t size) {
  set_has_uname();
  if (uname_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    uname_ = new ::std::string;
  }
  uname_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:db.UserData.uname)
}
inline ::std::string* UserData::mutable_uname() {
  set_has_uname();
  if (uname_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    uname_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:db.UserData.uname)
  return uname_;
}
inline ::std::string* UserData::release_uname() {
  clear_has_uname();
  if (uname_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = uname_;
    uname_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void UserData::set_allocated_uname(::std::string* uname) {
  if (uname_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete uname_;
  }
  if (uname) {
    set_has_uname();
    uname_ = uname;
  } else {
    clear_has_uname();
    uname_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:db.UserData.uname)
}

// optional int32 money = 3 [default = 0];
inline bool UserData::has_money() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void UserData::set_has_money() {
  _has_bits_[0] |= 0x00000004u;
}
inline void UserData::clear_has_money() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void UserData::clear_money() {
  money_ = 0;
  clear_has_money();
}
inline ::google::protobuf::int32 UserData::money() const {
  // @@protoc_insertion_point(field_get:db.UserData.money)
  return money_;
}
inline void UserData::set_money(::google::protobuf::int32 value) {
  set_has_money();
  money_ = value;
  // @@protoc_insertion_point(field_set:db.UserData.money)
}

// optional int32 last_login_time = 4 [default = 0];
inline bool UserData::has_last_login_time() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void UserData::set_has_last_login_time() {
  _has_bits_[0] |= 0x00000008u;
}
inline void UserData::clear_has_last_login_time() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void UserData::clear_last_login_time() {
  last_login_time_ = 0;
  clear_has_last_login_time();
}
inline ::google::protobuf::int32 UserData::last_login_time() const {
  // @@protoc_insertion_point(field_get:db.UserData.last_login_time)
  return last_login_time_;
}
inline void UserData::set_last_login_time(::google::protobuf::int32 value) {
  set_has_last_login_time();
  last_login_time_ = value;
  // @@protoc_insertion_point(field_set:db.UserData.last_login_time)
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace db

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_dbproto_2fuser_2eproto__INCLUDED
