
all:

install:
	cp hiredis/libhiredis* ../lib/
	cp lua/src/lua ../bin/lua
	cp lua/src/liblua.so ../lib/liblua.so
	sudo cp lua/src/liblua.so /usr/local/lib/liblua.so
	cp luajit/src/luajit ../bin/lua
	cp luajit/src/libluajit.so ../lib/liblua.so
	sudo cp luajit/src/libluajit.so /usr/local/lib/libluajit-5.1.2.dylib


