all:
	cd sys;make
	cd ae;make
	cd ar;make
	cd sendbuf;make
	cd recvbuf;make
	cd redis;make
	cd mysql;make
	cd pbc;make
	cd json;make
	cd socket;make
	cd stringpatch;make

install:
	cd sys;make install
	cd ae;make install
	cd ar;make install
	cd sendbuf;make install
	cd recvbuf;make install
	cd redis;make install
	cd mysql;make install
	cd pbc;make install
	cd json;make install
	cd socket;make install
	cd stringpatch;make install

clean:
	cd sys;make clean
	cd ae;make clean
	cd ar;make clean
	cd sendbuf;make clean
	cd recvbuf;make clean
	cd redis;make clean
	cd mysql;make clean
	cd pbc;make clean
	cd json;make clean
	cd socket;make clean
	cd stringpatch;make clean


