
all:
	../../bin/startsrv gatesrv1

game:
	../../bin/startsrv gamesrv1

gate:
	../../bin/startsrv gatesrv1

global:
	../../bin/startsrv globalsrv1

test:
	../../bin/pbtest login.login

initdb:
	../../bin/initdb
